serde support added
typst/biblatex pull request #14
Opened 2022-01-02 23:13 UTC by constraintAutomaton

I think it would be good to add support for [serde](https://serde.rs/) this way to user can convert the bib library to other formats more easily (for example store the references into a mongo database or conversion into another reference system)

2022-01-03 22:31 UTC, reknih commented
Thanks for your PR!

Could you make `serde` an optional feature? You'll just need to change your dependency declaration to
```toml
serde = { version = "1.0", optional = true }
```

and mark the `derive`d traits like this:
```rust
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
```

Please test whether the crate compiles with and without the feature enabled.

2022-01-04 03:25 UTC, constraintAutomaton commented
> Thanks for your PR!
> 
> Could you make `serde` an optional feature? You'll just need to change your dependency declaration to
> 
> ```toml
> serde = { version = "1.0", optional = true }
> ```
> 
> and mark the `derive`d traits like this:
> 
> ```rust
> #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
> ```
> 
> Please test whether the crate compiles with and without the feature enabled.

it's done, it compile with and without.

2022-01-04 07:43 UTC, reknih requested changes
Final style bits before merging

2022-01-04 07:43 UTC, reknih commented on Cargo.toml
> +serde = { version = "1.0.133", features = ["derive"], optional = true }
Drop the patch version here 
```suggestion
serde = { version = "1.0", features = ["derive"], optional = true }
```

2022-01-04 07:43 UTC, reknih commented on src/chunk.rs
>  #[derive(Debug, Clone, Eq, PartialEq)]
Switch around these two lines such that unconditional derives happen first

2022-01-04 07:43 UTC, reknih commented on src/lib.rs
>  #[derive(Debug, Clone)]
Switch the derives as above. Is there a reason for the additional blank doc-comment line?

2022-01-04 07:43 UTC, reknih commented on src/lib.rs
>  #[derive(Debug, Clone, Eq, PartialEq)]
Switch the derives as above.

2022-01-04 07:43 UTC, reknih commented on src/mechanics.rs
>  #[strum(serialize_all = "lowercase")]
Switch the derives as above. Keep both of them above the strum procmacro.

2022-01-04 21:35 UTC, reknih approved these changes
This looks good to merge now, thanks!

2022-01-04 21:36 UTC, merged